# Generated by Django 2.2.7 on 2019-11-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentuser',
            name='ending_date_for_commission_contract',
            field=models.DateField(null=True),
        ),
    ]
