# Generated by Django 2.2.7 on 2019-12-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20191124_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stack_name',
            new_name='stock_name',
        ),
    ]
