# Generated by Django 2.2.7 on 2019-12-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20191203_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrate',
            name='dividend_paid',
            field=models.FloatField(default=0),
        ),
    ]
