# Generated by Django 2.2.7 on 2019-12-07 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20191206_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrate',
            old_name='date',
            new_name='trading_date',
        ),
        migrations.RemoveField(
            model_name='currentrate',
            name='time',
        ),
        migrations.AddField(
            model_name='currentrate',
            name='time_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 7, 0, 55, 854910, tzinfo=utc)),
        ),
    ]
